# Generated by Django 4.1.9 on 2023-05-30 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="site",
            options={"ordering": ["domain"], "verbose_name": "site", "verbose_name_plural": "sites"},
        ),
    ]
